import { FalVideoTool } from "./falTypes";

const WAN_IMAGE_TO_VIDEO = "fal-ai/wan/v2.7/image-to-video";
const WAN_TEXT_TO_VIDEO = "fal-ai/wan/v2.7/text-to-video";
const FLASHTALK = "fal-ai/flashtalk";

const imageToVideoTools: FalVideoTool[] = [
  "Photo to Video",
  "Image to Video",
  "Dance Animation",
  "Dancing",
  "Running",
  "Walking",
  "Exercising",
  "Boxing",
  "Basketball",
  "Tennis",
  "Swimming",
  "Cycling",
  "Jumping",
  "Cooking",
  "Eating",
  "Shopping",
  "Driving",
  "Playing Music",
  "Singing",
  "Working Out",
  "Horse Riding",
  "Skateboarding",
  "Football Match Fan",
  "Football Stadium Celebration",
  "Football Fan Celebration",
  "Football Training",
  "Football Match",
  "Fan at Football Match",
  "Political Rally",
  "Political Rally Crowd",
  "Political Campaign",
  "Campaign Event",
  "Political Speech",
  "Fan at Political Rally",
  "Political Rally in Nairobi",
  "Political Rally in Washington DC",
  "Election Campaign",
  "Election Rally",
  "Public Demonstration",
  "Street Crowd",
  "Public Event",
  "Celebration Crowd",
  "Concert",
  "On Stage",
  "Party",
  "Red Carpet",
  "Fashion Show",
  "Model Photoshoot",
  "Wedding Celebration",
  "Birthday Party",
  "Family Celebration",
  "Graduation Celebration",
  "Beach Party",
  "Yacht Party",
  "Nightlife",
  "Restaurant",
  "Café",
  "Fine Dining",
  "Luxury Hotel",
  "Safari",
  "At the Beach",
  "Tropical Island",
  "Travel Reel",
  "Tourist in Nairobi",
  "Tourist in London",
  "Tourist in Paris",
  "Tourist in New York",
  "Tourist in Dubai",
  "Tourist in Tokyo",
  "Tourist in Singapore",
  "Tourist in Rome",
  "Tourist in Barcelona",
  "Tourist in Sydney",
  "Tourist in Washington DC",
  "Tourist at Eiffel Tower",
  "Tourist at Times Square",
  "Tourist at Great Wall of China",
  "Tourist at Pyramids of Egypt",
  "Tourist at White House",
  "Tourist at Buckingham Palace",
  "Tourist at Statue of Liberty",
  "Tourist at Colosseum",
  "Tourist at Taj Mahal",
  "Tourist at Mount Fuji",
  "Camping",
  "Campfire",
  "Waterfall Adventure",
  "Forest Adventure",
  "Desert Adventure",
  "Snow Adventure",
  "Hiking",
  "Mountain Climbing",
  "At the Airport",
  "Inside an Airplane",
  "Luxury Train",
  "Luxury Car",
  "Yacht",
  "Helicopter Ride",
  "Skydiving",
  "Surfing",
  "Scuba Diving",
  "Kayaking",
  "Skiing",
  "Snowboarding",
  "Wakeboarding",
  "Rock Climbing",
  "Paragliding",
  "Bungee Jumping",
  "Cinematic Video",
  "Cinematic Slow Motion",
  "Camera Zoom",
  "Camera Pan",
  "Camera Orbit",
  "Drone Shot",
  "Close-Up Shot",
  "Action Scene",
  "Movie Scene",
  "Short Film",
  "Trailer Video",
  "Transformation Video",
];

export const falModelByTool: Partial<Record<FalVideoTool, string>> = {
  "Text to Video": WAN_TEXT_TO_VIDEO,
  "Photo to Video": WAN_IMAGE_TO_VIDEO,
  "Image to Video": WAN_IMAGE_TO_VIDEO,
  "Talking Avatar": FLASHTALK,
  "AI Talking Avatar": FLASHTALK,
  "Talking Photo": FLASHTALK,
  "Lip Sync Video": FLASHTALK,
  "Singing Photo": FLASHTALK,
};

for (const tool of imageToVideoTools) {
  if (!(tool in falModelByTool)) {
    falModelByTool[tool] = WAN_IMAGE_TO_VIDEO;
  }
}
