export type FalVideoTool =
  | "Text to Video"
  | "Photo to Video"
  | "Image to Video"
  | "Talking Photo"
  | "Talking Avatar"
  | "AI Talking Avatar"
  | "Lip Sync Video"
  | "Singing Photo"
  | "AI News Presenter"
  | "AI Spokesperson"
  | "Virtual Influencer"
  | "AI Presenter"
  | "Talking News Anchor"
  | "Business Presenter"
  | "Product Presenter"
  | "Virtual Teacher"
  | "Virtual Tour Guide"
  | "Dance Animation"
  | "Dancing"
  | "AI Music Video Studio"
  | "Photo Music Video"
  | "Cinematic Video"
  | "Cinematic Slow Motion"
  | "Camera Zoom"
  | "Camera Pan"
  | "Camera Orbit"
  | "Drone Shot"
  | "Close-Up Shot"
  | "Action Scene"
  | "Movie Scene"
  | "Short Film"
  | "Trailer Video"
  | "Transformation Video"
  | "Running"
  | "Walking"
  | "Exercising"
  | "Boxing"
  | "Basketball"
  | "Tennis"
  | "Swimming"
  | "Cycling"
  | "Jumping"
  | "Cooking"
  | "Eating"
  | "Shopping"
  | "Driving"
  | "Playing Music"
  | "Singing"
  | "Working Out"
  | "Horse Riding"
  | "Skateboarding"
  | "Football Match Fan"
  | "Football Stadium Celebration"
  | "Football Fan Celebration"
  | "Football Training"
  | "Football Match"
  | "Fan at Football Match"
  | "Political Rally"
  | "Political Rally Crowd"
  | "Political Campaign"
  | "Campaign Event"
  | "Political Speech"
  | "Fan at Political Rally"
  | "Political Rally in Nairobi"
  | "Political Rally in Washington DC"
  | "Election Campaign"
  | "Election Rally"
  | "Public Demonstration"
  | "Street Crowd"
  | "Public Event"
  | "Celebration Crowd"
  | "Concert"
  | "On Stage"
  | "Party"
  | "Red Carpet"
  | "Fashion Show"
  | "Model Photoshoot"
  | "Wedding Celebration"
  | "Birthday Party"
  | "Family Celebration"
  | "Graduation Celebration"
  | "Beach Party"
  | "Yacht Party"
  | "Nightlife"
  | "Restaurant"
  | "Café"
  | "Fine Dining"
  | "Luxury Hotel"
  | "Safari"
  | "At the Beach"
  | "Tropical Island"
  | "Travel Reel"
  | "Tourist in Nairobi"
  | "Tourist in London"
  | "Tourist in Paris"
  | "Tourist in New York"
  | "Tourist in Dubai"
  | "Tourist in Tokyo"
  | "Tourist in Singapore"
  | "Tourist in Rome"
  | "Tourist in Barcelona"
  | "Tourist in Sydney"
  | "Tourist in Washington DC"
  | "Tourist at Eiffel Tower"
  | "Tourist at Times Square"
  | "Tourist at Great Wall of China"
  | "Tourist at Pyramids of Egypt"
  | "Tourist at White House"
  | "Tourist at Buckingham Palace"
  | "Tourist at Statue of Liberty"
  | "Tourist at Colosseum"
  | "Tourist at Taj Mahal"
  | "Tourist at Mount Fuji"
  | "Camping"
  | "Campfire"
  | "Waterfall Adventure"
  | "Forest Adventure"
  | "Desert Adventure"
  | "Snow Adventure"
  | "Hiking"
  | "Mountain Climbing"
  | "At the Airport"
  | "Inside an Airplane"
  | "Luxury Train"
  | "Luxury Car"
  | "Yacht"
  | "Helicopter Ride"
  | "Skydiving"
  | "Surfing"
  | "Scuba Diving"
  | "Kayaking"
  | "Skiing"
  | "Snowboarding"
  | "Wakeboarding"
  | "Rock Climbing"
  | "Paragliding"
  | "Bungee Jumping"
  | "Business Promo Video"
  | "Product Ad Generator"
  | "Real Estate Video"
  | "Event Promotion Video"
  | "Motivational Video"
  | "Story Generator"
  | "News Summary Video"
  | "News Slideshow Video"
  | "Educational Explainer Video"
  | "Quote Video"
  | "Graduation Video"
  | "Baby Shower Video"
  | "WhatsApp Status Maker"
  | "Facebook Reel Maker"
  | "TikTok Video Maker"
  | "Instagram Reel Maker"
  | "YouTube Shorts Maker"
  | "Obituary / Tribute Studio"
  | "Funeral Program Video"
  | "Church Announcement Video"
  | "Bible Verse Video"
  | "Crusade Promo Video"
  | "Youth Service Promo Video"
  | "Conference Promo Video";

export type FalVideoRequest = {
  tool: FalVideoTool;
  prompt: string;
  imageUrl?: string;
  imageFile?: File;
  audioUrl?: string;
  audioBlob?: Blob;
  durationSeconds: number;
  aspectRatio: "9:16" | "1:1" | "16:9";
};

export type FalVideoResult = {
  id: string;
  status: "queued" | "processing" | "completed" | "failed";
  videoUrl?: string;
  error?: string;
};
